### ISSUE TITLE
Повсюду в коде файла applet.js "reflesh", а не "refresh"

### ISSUE THREAD

**Issue by ava57r** [NaruTrey/timeout-libnaru.so#1]
Привет.
Повсюду в коде файла applet.js "reflesh", а не "refresh". Так задумано или опечатка?

**Comment by andrey-kun** [comment]
Да, это такой прикол на внимательность :)

**Comment by ava57r** [comment]
Я обратил внимание. Будет исправлено?

**Comment by andrey-kun** [comment]
Нет
